# Generated by Django 5.0.7 on 2024-07-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
